login = "                                      Log In                                        "
username = "Username"
newusername = "New Username"
newpassword = "New Password"
password = "Password"
register = "                     Register                    "
go = "                         Go                         "
cancel = "        Cancel       "
search = "                                      Search                                      "
output = "         Output History          "
input = "         Input History         "
shh = "              Incognito             "
cancel2 = "              Cancel             "
line = "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
inputline = "=-=-=-=-=-=-=-= Input History =-=-=-=-=-=-=-=\n"
outputline = "=-=-=-=-=-=-=-= Output History =-=-=-=-=-=-=-=\n"
